### ISSUE TITLE
viewport-fit is flagged as invalid in viewport meta tag

### ISSUE THREAD

**Issue by Kilian** [rviscomi/capo.js#110]
In 1.5.2 `viewport-fit= cover` is flagged as invalid. While it's indeed not mentioned on [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag), I think it should not be flagged as an issue because both [iOS](https://webkit.org/blog/7929/designing-websites-for-iphone-x/) and [Android](https://web.dev/learn/pwa/app-design) implement it.

**Comment by rviscomi** [comment]
Oh interesting, thanks for pointing that out. I'll carve out an exception for `viewport-fit`.

**Comment by Kilian** [comment]
Would you like me to send in a PR?

**Comment by rviscomi** [comment]
That'd be appreciated, thank you!
