### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by Aslemammad** [rviscomi/capo.js#17]
Can we have a chrome extension for capo.js? Great work btw.

**Comment by rviscomi** [comment]
Yeah that could be useful. What sort of features would you be looking to see out of it?

**Comment by Aslemammad** [comment]
Thanks, the thing I want is accessibility, I want it to analyze most pages and when I click on the icon, it shows me things that currently shows in the console log.

**Comment by rviscomi** [comment]
Have you tried the [bookmarklet](https://github.com/rviscomi/capo.js#how-to-use-it)?

**Comment by Aslemammad** [comment]
Thank you so much for the effort mate, I really appreciate it.
