### ISSUE TITLE
Try fetching/parsing HTML client-side

### ISSUE THREAD

**Issue by rviscomi** [rviscomi/capo.js#29]
In https://github.com/HTTPArchive/custom-metrics/pull/12#discussion_r883150296 @jroakes shared a screencast of some code for a document to parse its own body. Taking inspiration from that, I've modified the code a bit to produce a snippet that yields the entire contents of the static (server-rendered) `<head>`:

```js
async function parse_own_body() {
    const url = document.location.href;
    let response = await fetch(url);
    let responseText = await response.text();
    return responseText;
}

let html = await parse_own_body();
html = html.replace(/(<\/?)(head)/ig, '$1static-head');
const staticDoc = document.implementation.createHTMLDocument("New Document");
staticDoc.documentElement.innerHTML = html;
const staticHead = staticDoc.querySelector('static-head');
staticHead;
```

The insight I had was that by renaming the `head` element to anything else, we can circumvent the HTML parser's behavior to truncate on invalid elements. Combined with fetching the raw HTML from the server, this should give us a pristine copy of the original `head` to use for capo analysis.

<img width="1239" alt="Screen Shot 2023-06-20 at 9 28 29 PM" src="https://github.com/rviscomi/capo.js/assets/1120896/94d32a08-ee26-4600-bf5b-836e46fa7f73">

This screenshot shows it working on the NYT site.

It should be possible to drop this approach into capo.js and fall back to the dynamic `head` as needed—I'd imagine some CSP rules blocking this use of `fetch`.

There might be sandbox limitations of doing something like this in a Chrome extension. I'll investigate.

**Comment by rviscomi** [comment]
Amusing side note: while testing this I discovered that the raw NYT HTML actually includes two `<head>` sections 😄 

<img width="244" alt="image" src="https://github.com/rviscomi/capo.js/assets/1120896/a6c160e7-e1ac-4aee-afa0-7a88b92bd931">

**Comment by janwillemwilmsen** [comment]
Maybe the NY Times changed something, but now there are 3 <head> tags in the html.

**Comment by rviscomi** [comment]
Now I count 4 😱

<img width="571" alt="image" src="https://github.com/rviscomi/capo.js/assets/1120896/caa582e3-c92b-4bc3-867b-919165c36018">
