### ISSUE TITLE
Capo extension crashes for my site

### ISSUE THREAD

**Issue by stefanjudis** [rviscomi/capo.js#31]
Hey Rick, I hope you're well. I just wanted to play with the new extension and it's crashing for my site. 🫣

Might be because there's too much inline styles? 😅

<img width="1917" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/66fad2f6-330e-4394-9a94-2b125edf9de7">

**Comment by rviscomi** [comment]
Oh no 😱 

Can you confirm which version of the extension you're using? v1.2 was just published today. Go to `chrome://extensions/` to check:

<img width="415" alt="image" src="https://github.com/rviscomi/capo.js/assets/1120896/b252c7f3-f56e-4f6f-b02b-ca143878f551">

Also, if there's an "Errors" button there, can you click it and share any error messages?

FWIW when I load up your site with 1.2 it seems to work normally.

<img width="1541" alt="Screen Shot 2023-06-23 at 9 38 39 AM" src="https://github.com/rviscomi/capo.js/assets/1120896/4387cb5f-2672-4c51-bdf7-9062f55a7e56">

The only other thing I can think of is maybe some bad combination of extensions. If all else fails, maybe you could try disabling them in batches to see if that helps narrow it down.

**Comment by rviscomi** [comment]
Could you also try running the [snippet](https://github.com/rviscomi/capo.js/blob/main/capo.js) in DevTools to see if that works?

**Comment by stefanjudis** [comment]
Hmm... same thing when pasting.

![Uploading image.png…]()

**Comment by rviscomi** [comment]
Any console/network errors?

**Comment by stefanjudis** [comment]
Thanks for the swift reply!

I'm on `1.2` and Chrome `Version 114.0.5735.133 (Official Build) (x86_64)`.  🫣

<img width="705" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/ece3d60c-703c-49ac-963c-5537c9f70757">

> Also, if there's an "Errors" button there, can you click it and share any error messages?

I don't see an errors button. :/ 

I also disabled all other extensions. 

<img width="1286" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/0885c06a-1f83-4e2d-85ea-a6af42f1920f">

Pasting the snippet into the console leads to the same crashing result.

<img width="1915" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/11de1b4e-9e2c-440a-9614-3c4e093f7f52">

> Edit: I also see you have CSP set up (it's blocking https://ingesteer.services-prod.nsvcs.net/rum_collection by the way!) but it doesn't seem to be blocking capo's [fetch](https://github.com/rviscomi/capo.js/blob/main/capo.js?rgh-link-date=2023-06-23T13%3A43%3A22Z#L62).

Haha yeah, I try to be a good web citizen and it stands in the way soooooo much. :D  

There are also no exceptions or something. 

<img width="417" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/266c3bb0-52a9-475a-ab69-987afcdb4987">

-------

Oh boy, I see that this is report isn't debuggable if it works for you. 😅

**Comment by rviscomi** [comment]
Does it work on any other pages?

**Comment by stefanjudis** [comment]
Jep. 😅

<img width="659" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/d0f49bee-ccbf-45f9-8fe3-d23f0c0bd458">


<img width="641" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/5ca23cd2-6b53-4ea1-9263-6c5f6e132dc6">

**Comment by rviscomi** [comment]
Hmm I'll DM you, maybe we can debug over VC

**Comment by rviscomi** [comment]
To summarize:

- the site crashes for both the extension and the snippet
  - when the extension crashes we get the error `"extension manifest must request permission to access the respective host."` (try/catch logs the error but still crashes)
  - no error message when the snippet crashes
- crashes only on stefanjudis.com, not other sites
  - crashes even on local build of the site, no CSP
- crashes only on Stefan's computer, not mine despite same version of Chrome and extension/snippet
  - crashes even when no other extensions are enabled
  - crashes for both the official build of the extension and a locally installed development version
- crashes only on Chrome stable, not on canary (!)

@stefanjudis as a follow up, could you try running [version 1.1 of the snippet](https://raw.githubusercontent.com/rviscomi/capo.js/9c40a1db67eeba101b4766c1ce0b089c97805141/capo.js)? This one doesn't have the validation logic or static head parsing, so if it works there must be a bug in the new code.

**Comment by stefanjudis** [comment]
Huh! Progress!

[`1.1` version of the snippet](https://raw.githubusercontent.com/rviscomi/capo.js/9c40a1db67eeba101b4766c1ce0b089c97805141/capo.js) (the one you linked) works.

<img width="1917" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/71c2b66b-e4f8-422c-8ec6-b2bc4fc05b88">

[Current `main` crashes Chrome](https://raw.githubusercontent.com/rviscomi/capo.js/main/capo.js).

<img width="1916" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/116412e6-ff29-41f3-b3ce-18ec0b4a3c8c">

**Comment by rviscomi** [comment]
Very interesting! The logic for getting the static head is this:

```js
let head;

let isStaticHead = false;


async function getStaticHTML() {
  const url = document.location.href;
  const response = await fetch(url);
  return await response.text();
}

async function getStaticOrDynamicHead() {
  if (head) {
    return head;
  }

  try {
    let html = await getStaticHTML();
    html = html.replace(/(<\/?)(head)/ig, '$1static-head');
    const staticDoc = document.implementation.createHTMLDocument('New Document');
    staticDoc.documentElement.innerHTML = html;
    head = staticDoc.querySelector('static-head');
    
    if (head) {
      isStaticHead = true;
    } else {
      head = document.head;
    }
  } catch {
    head = document.head;
  }
  return head;
}

await getStaticOrDynamicHead();
```

Does that trigger the crash? Does it return a `<head>` or `<static-head>` element?

I think we're getting close!

**Comment by stefanjudis** [comment]
It looks indeed like this is crashing it.

https://github.com/rviscomi/capo.js/assets/962099/20f76d8b-2b68-4821-856e-319ea7d2923c

But only initially. With devtools open, after a refresh it seems to work.

**Comment by rviscomi** [comment]
It looks like you're running scripts 3 times: the first time is the `getStaticOrDynamicHead` script, which crashes the tab, the second and third times you're running the v1.1 script, which works. Or are you saying the `getStaticOrDynamicHead` script works on the second/third try?

Now that we know that's the script that causes the crash, I wonder if we can narrow it down further.

Just `getStaticHTML`:

```js
async function getStaticHTML() {
  const url = document.location.href;
  const response = await fetch(url);
  return await response.text();
}
await getStaticHTML();
```

or just `getStaticOrDynamicHead` (with example.com HTML):

```js
let head;
let isStaticHead = false;
async function getStaticOrDynamicHead() {
  if (head) {
    return head;
  }

  try {
    let html = `<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href="https://www.iana.org/domains/example">More information...</a></p>\n</div>\n</body>\n</html>\n`;
    html = html.replace(/(<\/?)(head)/ig, '$1static-head');
    const staticDoc = document.implementation.createHTMLDocument('New Document');
    staticDoc.documentElement.innerHTML = html;
    head = staticDoc.querySelector('static-head');
    
    if (head) {
      isStaticHead = true;
    } else {
      head = document.head;
    }
  } catch (e) {
    console.error('Capo error', e);
    head = document.head;
  }
  return head;
}

await getStaticOrDynamicHead();
```

Would you be able to try both and report back what happens?

**Comment by stefanjudis** [comment]
This is so strange—the two snippets from the preview comment work alone.

But the snippet here: https://github.com/rviscomi/capo.js/issues/31#issuecomment-1604636090 breaks Chrome.


https://github.com/rviscomi/capo.js/assets/962099/5f55a376-f6d0-4c6f-b9ad-da0777a509f3

`staticDoc.documentElement.innerHTML = html;` seems to be the issue.

**Comment by rviscomi** [comment]
Could you share what this returns? I wonder if we're getting different HTML back.

```
async function getStaticHTML() {
  const url = document.location.href;
  const response = await fetch(url);
  return await response.text();
}
await getStaticHTML();
```

**Comment by stefanjudis** [comment]
Just getting the static HTML works fine. 

<img width="702" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/8b6fb0b8-cf7a-4ac7-b29c-b6b390ad118a">

Logging the HTML before works two and looks correctly.

<img width="718" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/00c042a2-acf7-4826-8923-d3b79267ccbd">

It looks like it's cooking on the large HTML being assigned to the static doc. 

It looks like a weird Chrome bug which is fixed in canary already. Should we just wait if it resolves itself with the next Chrome major release?

**Comment by rviscomi** [comment]
I'm sad we couldn't find the exact bug, but waiting for 115 sounds good to me. Should be out in a couple of weeks.

**Comment by rviscomi** [comment]
@stefanjudis if you go to the [extension options](https://rviscomi.github.io/capo.js/user/config/#configuring-the-extension) and deselect "Prefer to evaluate the static, server-rendered `<head>`" my hope is that it will circumvent the bug you hit 🤞

**Comment by stefanjudis** [comment]
Works!!! Still crashing in default settings with Chrome 114 but when deselecting it works 💯

<img width="1327" alt="image" src="https://github.com/rviscomi/capo.js/assets/962099/4e065914-af4f-4d99-a61b-47fea7bae7be">
