### ISSUE TITLE
Asynchronous or Synchronous scripts?

### ISSUE THREAD

**Issue by dougouverson** [rviscomi/capo.js#96]
According to https://rviscomi.github.io/capo.js/user/rules/#-8-asynchronous-scripts 

`<script async src>`

The following scripts were included in the Asynchronous scripts order:

```
<script type="text/javascript"> document.documentElement.className = 'js'; </script>
<script type="text/javascript" src=""></script>
<script type="text/javascript" src="" id="jquery-migrate-js"></script>
```

I thought maybe they should have been included in Synchronous scripts?

**Comment by rviscomi** [comment]
Could you share a reproducible example using the demo page?
https://rviscomi.github.io/capo.js/user/demo/?url=https://www.example.com/

**Comment by dougouverson** [comment]
Not that I can see:

![Page 2](https://github.com/rviscomi/capo.js/assets/4654813/41b3c1f9-0807-40e2-8bd1-bce499b41ffb)
![Page 3](https://github.com/rviscomi/capo.js/assets/4654813/ab163be9-a9e2-4a31-b14a-46bd5820cc91)

**Comment by rviscomi** [comment]
Ok thanks, looks like this is WAI

**Comment by dougouverson** [comment]
I'm sorry, what is WAI?

**Comment by rviscomi** [comment]
Working as intended

**Comment by rviscomi** [comment]
Yeah, asynchronous scripts are specifically defined as [`script[async]`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#async), but that script has a [data attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) coincidentally named `data-cfasync`. Data attributes are just ways to stuff information into DOM elements and browsers don't behave any differently when they're encountered.

**Comment by dougouverson** [comment]
Thanks, Rick, for the explanation!

WAI !
